<?php

use Illuminate\Database\Seeder;

class AccessoriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('accessories')->insert([
//            [
//                'user_id' => 1,
//                'video_id' => str_random(7),
//                'start_video' => 'none',
//                'images' => 'http://'.str_random(3).'.jpg',
//                'thumbnail' => 'http://'.str_random(3).'.jpg',
//                'advantage' => str_random(7).', '.str_random(7).', '.str_random(7),
//                'shortcomings' => str_random(7).', '.str_random(7).', '.str_random(7),
//                'text' => str_random(300),
//                'rating' => 3.5,
//                'accessory_id' => 1,
//                'brand' => str_random(10),
//                'model' => str_random(10),
//                'price_rub' => 100,
//                'price_usd' => 'none',
//                'store' => 'Aly',
//                'date_purchase' => '10.10.2010',
//                'review' => true,
//                'tags' => 'tag-1, tag-2',
//            ],
            [
                'user_id' => 3,
                'video_id' => str_random(7),
                'start_video' => 'none',
                'images' => 'http://'.str_random(3).'.jpg',
                'thumbnail' => 'http://'.str_random(3).'.jpg',
                'advantage' => str_random(7).', '.str_random(7).', '.str_random(7),
                'shortcomings' => str_random(7).', '.str_random(7).', '.str_random(7),
                'text' => str_random(300),
                'rating' => 4.5,
                'accessory_id' => 1,
                'brand' => str_random(10),
                'model' => str_random(10),
                'price_rub' => 2000,
                'price_usd' => 'none',
                'store' => 'Aly',
                'date_purchase' => '10.10.2010',
                'review' => true,
                'tags' => 'tag-1, tag-2',
            ],
            [
                'user_id' => 2,
                'video_id' => str_random(7),
                'start_video' => 'none',
                'images' => 'http://'.str_random(3).'.jpg',
                'thumbnail' => 'http://'.str_random(3).'.jpg',
                'advantage' => str_random(7).', '.str_random(7).', '.str_random(7),
                'shortcomings' => str_random(7).', '.str_random(7).', '.str_random(7),
                'text' => str_random(300),
                'rating' => 2.5,
                'accessory_id' => 2,
                'brand' => str_random(10),
                'model' => str_random(10),
                'price_rub' => 350,
                'price_usd' => 'none',
                'store' => 'Aly',
                'date_purchase' => '10.10.2010',
                'review' => true,
                'tags' => 'tag-1, tag-2',
            ],
            [
                'user_id' => 1,
                'video_id' => str_random(7),
                'start_video' => 'none',
                'images' => 'http://'.str_random(3).'.jpg',
                'thumbnail' => 'http://'.str_random(3).'.jpg',
                'advantage' => str_random(7).', '.str_random(7).', '.str_random(7),
                'shortcomings' => str_random(7).', '.str_random(7).', '.str_random(7),
                'text' => str_random(300),
                'rating' => 3,
                'accessory_id' => 1,
                'brand' => str_random(10),
                'model' => str_random(10),
                'price_rub' => 600,
                'price_usd' => 'none',
                'store' => 'Aly',
                'date_purchase' => '10.10.2010',
                'review' => true,
                'tags' => 'tag-1, tag-2',
            ],
            [
                'user_id' => 3,
                'video_id' => str_random(7),
                'start_video' => 'none',
                'images' => 'http://'.str_random(3).'.jpg',
                'thumbnail' => 'http://'.str_random(3).'.jpg',
                'advantage' => str_random(7).', '.str_random(7).', '.str_random(7),
                'shortcomings' => str_random(7).', '.str_random(7).', '.str_random(7),
                'text' => str_random(300),
                'rating' => 4.5,
                'accessory_id' => 2,
                'brand' => str_random(10),
                'model' => str_random(10),
                'price_rub' => 380,
                'price_usd' => 'none',
                'store' => 'Aly',
                'date_purchase' => '10.10.2010',
                'review' => true,
                'tags' => 'tag-1, tag-2',
            ],
            [
                'user_id' => 2,
                'video_id' => str_random(7),
                'start_video' => 'none',
                'images' => 'http://'.str_random(3).'.jpg',
                'thumbnail' => 'http://'.str_random(3).'.jpg',
                'advantage' => str_random(7).', '.str_random(7).', '.str_random(7),
                'shortcomings' => str_random(7).', '.str_random(7).', '.str_random(7),
                'text' => str_random(300),
                'rating' => 3.5,
                'accessory_id' => 3,
                'brand' => str_random(10),
                'model' => str_random(10),
                'price_rub' => 490,
                'price_usd' => 'none',
                'store' => 'Aly',
                'date_purchase' => '10.10.2010',
                'review' => true,
                'tags' => 'tag-1, tag-2',
            ],
            [
                'user_id' => 1,
                'video_id' => str_random(7),
                'start_video' => 'none',
                'images' => 'http://'.str_random(3).'.jpg',
                'thumbnail' => 'http://'.str_random(3).'.jpg',
                'advantage' => str_random(7).', '.str_random(7).', '.str_random(7),
                'shortcomings' => str_random(7).', '.str_random(7).', '.str_random(7),
                'text' => str_random(300),
                'rating' => 5,
                'accessory_id' => 3,
                'brand' => str_random(10),
                'model' => str_random(10),
                'price_rub' => 500,
                'price_usd' => 'none',
                'store' => 'Aly',
                'date_purchase' => '10.10.2010',
                'review' => true,
                'tags' => 'tag-1, tag-2',
            ],
            [
                'user_id' => 3,
                'video_id' => str_random(7),
                'start_video' => 'none',
                'images' => 'http://'.str_random(3).'.jpg',
                'thumbnail' => 'http://'.str_random(3).'.jpg',
                'advantage' => str_random(7).', '.str_random(7).', '.str_random(7),
                'shortcomings' => str_random(7).', '.str_random(7).', '.str_random(7),
                'text' => str_random(300),
                'rating' => 3.5,
                'accessory_id' => 1,
                'brand' => str_random(10),
                'model' => str_random(10),
                'price_rub' => 700,
                'price_usd' => 'none',
                'store' => 'Aly',
                'date_purchase' => '10.10.2010',
                'review' => true,
                'tags' => 'tag-1, tag-2',
            ],
            [
                'user_id' => 2,
                'video_id' => str_random(7),
                'start_video' => 'none',
                'images' => 'http://'.str_random(3).'.jpg',
                'thumbnail' => 'http://'.str_random(3).'.jpg',
                'advantage' => str_random(7).', '.str_random(7).', '.str_random(7),
                'shortcomings' => str_random(7).', '.str_random(7).', '.str_random(7),
                'text' => str_random(300),
                'rating' => 4,
                'accessory_id' => 2,
                'brand' => str_random(10),
                'model' => str_random(10),
                'price_rub' => 1020,
                'price_usd' => 'none',
                'store' => 'Aly',
                'date_purchase' => '10.10.2010',
                'review' => true,
                'tags' => 'tag-1, tag-2',
            ],
            [
                'user_id' => 1,
                'video_id' => str_random(7),
                'start_video' => 'none',
                'images' => 'http://'.str_random(3).'.jpg',
                'thumbnail' => 'http://'.str_random(3).'.jpg',
                'advantage' => str_random(7).', '.str_random(7).', '.str_random(7),
                'shortcomings' => str_random(7).', '.str_random(7).', '.str_random(7),
                'text' => str_random(300),
                'rating' => 5,
                'accessory_id' => 1,
                'brand' => str_random(10),
                'model' => str_random(10),
                'price_rub' => 1400,
                'price_usd' => 'none',
                'store' => 'Aly',
                'date_purchase' => '10.10.2010',
                'review' => true,
                'tags' => 'tag-1, tag-2',
            ],
        ]);

    }
}
